export const JNF_DATA = [
  {
    id: 1,
    role: 'Analytics',
    createdBy: 'Shivam',
    company: 'Company1',
    createdOn: 'Date1',
    lastEditedOn: 'Date1',
  },
  {
    id: 2,
    role: 'Consulting',
    createdBy: 'Shyam',
    company: 'Company2',
    createdOn: 'Date2',
    lastEditedOn: 'Date2',
  },
  {
    id: 3,
    role: 'Core(Technical)',
    createdBy: 'Mohan Kumar',
    company: 'Company3',
    createdOn: 'Date3',
    lastEditedOn: 'Date3',
  },
  {
    id: 4,
    role: 'BFSI',
    createdBy: 'Utkarsh',
    company: 'Company4',
    createdOn: 'Date4',
    lastEditedOn: 'Date4',
  },
  {
    id: 5,
    role: 'IT/SOFTWARE',
    createdBy: 'Aryan',
    company: 'Company5',
    createdOn: 'Date5',
    lastEditedOn: 'Date5',
  },
  {
    id: 6,
    role: 'Ed TECH',
    createdBy: 'Ramanujam',
    company: 'Company6',
    createdOn: 'Date6',
    lastEditedOn: 'Date6',
  },
  {
    id: 7,
    role: 'E-COMMERCE',
    createdBy: 'Prakash',
    company: 'Company7',
    createdOn: 'Date7',
    lastEditedOn: 'Date7',
  },
  {
    id: 8,
    role: 'Analytics',
    createdBy: 'Shohail',
    company: 'Company1',
    createdOn: 'Date1',
    lastEditedOn: 'Date1',
  },
  {
    id: 9,
    role: 'Consulting',
    createdBy: 'Saksham',
    company: 'Company2',
    createdOn: 'Date2',
    lastEditedOn: 'Date2',
  },
  {
    id: 10,
    role: 'IT/SOFTWARE',
    createdBy: 'Prakhar',
    company: 'Company5',
    createdOn: 'Date5',
    lastEditedOn: 'Date5',
  },
  {
    id: 11,
    role: 'IT/SOFTWARE',
    createdBy: 'Nitish',
    company: 'Company5',
    createdOn: 'Date5',
    lastEditedOn: 'Date5',
  },
];
