export const JNF_DATA = [
  {
    id: 1,
    role: 'Analytics',
    createdBy: 'Shivam',
    company: 'Company1',
    createdOn: 'Date1',
    lastEditedOn: 'Date1',
  },
  {
    id: 2,
    role: 'Consulting',
    createdBy: 'Shyam',
    company: 'Company2',
    createdOn: 'Date2',
    lastEditedOn: 'Date2',
  },
  {
    id: 3,
    role: 'Core(Technical)',
    createdBy: 'Mohan Kumar',
    company: 'Company3',
    createdOn: 'Date3',
    lastEditedOn: 'Date3',
  },
  {
    id: 4,
    role: 'BFSI',
    createdBy: 'Utkarsh',
    company: 'Company4',
    createdOn: 'Date4',
    lastEditedOn: 'Date4',
  },
  {
    id: 5,
    role: 'IT/SOFTWARE',
    createdBy: 'Aryan',
    company: 'Company5',
    createdOn: 'Date5',
    lastEditedOn: 'Date5',
  },
  {
    id: 6,
    role: 'Ed TECH',
    createdBy: 'Ramanujam',
    company: 'Company6',
    createdOn: 'Date6',
    lastEditedOn: 'Date6',
  },
  {
    id: 7,
    role: 'E-COMMERCE',
    createdBy: 'Prakash',
    company: 'Company7',
    createdOn: 'Date7',
    lastEditedOn: 'Date7',
  },
  {
    id: 8,
    role: 'Analytics',
    createdBy: 'Shohail',
    company: 'Company1',
    createdOn: 'Date1',
    lastEditedOn: 'Date1',
  },
  {
    id: 9,
    role: 'Consulting',
    createdBy: 'Saksham',
    company: 'Company2',
    createdOn: 'Date2',
    lastEditedOn: 'Date2',
  },
  {
    id: 10,
    role: 'IT/SOFTWARE',
    createdBy: 'Prakhar',
    company: 'Company5',
    createdOn: 'Date5',
    lastEditedOn: 'Date5',
  },
  {
    id: 11,
    role: 'IT/SOFTWARE',
    createdBy: 'Nitish',
    company: 'Company5',
    createdOn: 'Date5',
    lastEditedOn: 'Date5',
  },
];

export const JNF_FORM_DATA = {
  'company-overview': {
    name: 'Google',
    website: 'https://www.google.com',
    category: 'IT',
  },
  'job-details': {
    designation: 'SDE',
    place: 'Delhi',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita, consequuntur.',
  },
  'salary-details': {
    ctc: 25,
    'ctc-breakup': 'Lorem ipsum dolor sit amet.',
    'bond-details': 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
  },
  'contact-details': {
    primary: {
      name: 'Lorem, ipsum dolor.',
      designation: 'HR',
      email: 'example@gmail.com',
      mobile: 8575456321,
      name: 'Lorem, ipsum dolor.',
      designation: 'HR',
      email: 'example@gmail.com',
      mobile: 8575456321,
    },
    secondary: {
      name: 'Lorem, ipsum dolor.',
      designation: 'HR',
      email: 'example@gmail.com',
      mobile: 8575456321,
    },
  },
  'eligible-courses': {
    '4year': [
      'Chemical Engineering',
      'Civil Engineering',
      'Computer Science and Engineering',
      'Electrical Engineering',
      'Engineering Physics',
    ],
    '5year': ['Computer Science & Engineering', 'Applied Geology'],
    'skill-based': ['C, C++, Java, Python, etc.', 'AI/ ML/DL, Data Science'],
    jam: ['Applied Geology'],
    '2-year-mtech': [
      'Geo Exploration',
      'Engineering Geology',
      'Communication & Signal Processing',
      'Optoelectronics & Optical Communication Engineering',
      'RF and Microwave Engineering',
    ],
    '2-year-mba': ['Business Analytics', 'Finance', 'Marketing'],
    '2-year msc': ['Chemistry', 'Mathematics & Computing'],
    phd: [
      'Chemistry',
      'Applied Geology',
      'Physics',
      'Electrical Engineering',
      'Mechanical Engineering',
      'Mining Engineering',
      'Petroleum Engineering',
    ],
  },
  'selection-procedure': {
    'Resume Shortlisting': true,
    'Type of Test': 'Technical',
    'other-qualification-rounds': ['GD', 'Interview'],
    totalRound: 3,
    'number-of-offers': '20-25',
    'eligibility-criteria': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur, possimus.',
  },
};
